blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/x-neon-nexus-o/MovieMania/discussions
    about: Have a question? Start a discussion instead of opening an issue.
